import {
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
} from "node:fs";
import { dirname } from "node:path";
import {
  claudeUserConfigPath,
  claudeProjectMcpPath,
  codexHomeConfigPath,
  codexLocalConfigPath,
  codexLocalHome,
  IS_WIN,
} from "./paths.js";

// We resolve to @latest at runtime — never pin in MCP entries.
// Keeps users on freshest MCP without re-running init.
const MCP_PACKAGE = "@inbetweenai/mcp";

const MCP_BLOCK_START = "# === inbetween (auto-generated by @inbetweenai/cli) ===";
const MCP_BLOCK_END = "# === end inbetween ===";

interface ClaudeJson {
  mcpServers?: Record<string, any>;
  [k: string]: any;
}

function readClaudeJson(path: string): ClaudeJson {
  if (!existsSync(path)) return {};
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    return {};
  }
}

/** Write Claude MCP entry. `local=true` writes <cwd>/.mcp.json (project-scoped). */
export function writeClaudeMcp(opts: {
  configFile: string; // absolute path to InBetween config.json
  local?: boolean;
  cwd?: string;
}): string {
  const cwd = opts.cwd || process.cwd();
  const path = opts.local ? claudeProjectMcpPath(cwd) : claudeUserConfigPath();
  const json = readClaudeJson(path);
  json.mcpServers = json.mcpServers || {};
  // Drop old agentgram entry if present (rebrand cleanup).
  if (json.mcpServers.agentgram) delete json.mcpServers.agentgram;
  json.mcpServers.inbetween = IS_WIN
    ? {
        command: "cmd",
        args: ["/c", "npx", "-y", MCP_PACKAGE],
        env: { INBETWEEN_CONFIG_PATH: opts.configFile },
      }
    : {
        command: "npx",
        args: ["-y", MCP_PACKAGE],
        env: { INBETWEEN_CONFIG_PATH: opts.configFile },
      };
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(json, null, 2) + "\n");
  return path;
}

export function removeClaudeMcp(opts: { local?: boolean; cwd?: string }): string | null {
  const cwd = opts.cwd || process.cwd();
  const path = opts.local ? claudeProjectMcpPath(cwd) : claudeUserConfigPath();
  if (!existsSync(path)) return null;
  const json = readClaudeJson(path);
  if (!json.mcpServers || !json.mcpServers.inbetween) return null;
  delete json.mcpServers.inbetween;
  writeFileSync(path, JSON.stringify(json, null, 2) + "\n");
  return path;
}

/**
 * Strip ANY existing `[mcp_servers.inbetween]` section from the TOML —
 * regardless of whether it was wrapped in our marker comments or written
 * raw by an older installer / by the user. Idempotent.
 */
function stripExistingInbetweenBlock(toml: string): string {
  let out = toml;

  // 1. Strip our marker block (current format).
  if (out.includes(MCP_BLOCK_START) && out.includes(MCP_BLOCK_END)) {
    const s = out.indexOf(MCP_BLOCK_START);
    const e = out.indexOf(MCP_BLOCK_END) + MCP_BLOCK_END.length;
    out = out.slice(0, s) + out.slice(e);
  }

  // 2. Strip the legacy `(@inbetweenai/install)` marker block.
  const LEGACY_START = "# === inbetween (auto-generated by @inbetweenai/install) ===";
  if (out.includes(LEGACY_START) && out.includes(MCP_BLOCK_END)) {
    const s = out.indexOf(LEGACY_START);
    const e = out.indexOf(MCP_BLOCK_END, s) + MCP_BLOCK_END.length;
    out = out.slice(0, s) + out.slice(e);
  }

  // 3. Strip any raw `[mcp_servers.inbetween]` section (no markers). The
  //    section runs from its header until the next top-level `[` header
  //    or end of file. We also remove `[mcp_servers.inbetween.<sub>]`
  //    subsections that follow.
  const lines = out.split("\n");
  const next: string[] = [];
  let inBlock = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (
      trimmed === "[mcp_servers.inbetween]" ||
      trimmed.startsWith("[mcp_servers.inbetween.")
    ) {
      inBlock = true;
      continue;
    }
    if (inBlock && trimmed.startsWith("[") && !trimmed.startsWith("[mcp_servers.inbetween")) {
      inBlock = false;
    }
    if (!inBlock) next.push(line);
  }
  return next.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

/** Write Codex MCP entry. `local=true` writes <cwd>/.inbetween/codex/config.toml (used with CODEX_HOME). */
export function writeCodexMcp(opts: {
  configFile: string; // absolute path to InBetween config.json
  local?: boolean;
  cwd?: string;
}): string {
  const cwd = opts.cwd || process.cwd();
  const path = opts.local ? codexLocalConfigPath(cwd) : codexHomeConfigPath();
  let existing = "";
  if (existsSync(path)) {
    try {
      existing = readFileSync(path, "utf-8");
    } catch {}
  }
  // Idempotent: nuke any existing inbetween block so we don't end up with
  // duplicates that crash Codex's TOML parser.
  existing = stripExistingInbetweenBlock(existing);

  const escapedConfigFile = opts.configFile.replace(/\\/g, "\\\\");
  const command = IS_WIN ? "cmd" : "npx";
  const args = IS_WIN ? ["/c", "npx", "-y", MCP_PACKAGE] : ["-y", MCP_PACKAGE];
  const argsToml = JSON.stringify(args);
  const block = `${MCP_BLOCK_START}
[mcp_servers.inbetween]
command = "${command}"
args = ${argsToml}
env = { INBETWEEN_CONFIG_PATH = "${escapedConfigFile}", INBETWEEN_DISABLE_WS = "1" }
startup_timeout_sec = 30
${MCP_BLOCK_END}
`;
  const next = (existing.trim() + "\n\n" + block).trimStart();
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, next);
  return path;
}

export function removeCodexMcp(opts: { local?: boolean; cwd?: string }): string | null {
  const cwd = opts.cwd || process.cwd();
  const path = opts.local ? codexLocalConfigPath(cwd) : codexHomeConfigPath();
  if (!existsSync(path)) return null;
  const existing = readFileSync(path, "utf-8");
  const stripped = stripExistingInbetweenBlock(existing);
  if (stripped === existing) return null;
  writeFileSync(path, stripped);
  return path;
}

export { codexLocalHome };
