import {
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
} from "node:fs";
import { dirname } from "node:path";
import {
  claudeUserConfigPath,
  claudeProjectMcpPath,
  codexHomeConfigPath,
  codexLocalConfigPath,
  codexLocalHome,
  IS_WIN,
} from "./paths.js";

// We resolve to @latest at runtime — never pin in MCP entries.
// Keeps users on freshest MCP without re-running init.
const MCP_PACKAGE = "@inbetweenai/mcp";

const MCP_BLOCK_START = "# === inbetween (auto-generated by @inbetweenai/cli) ===";
const MCP_BLOCK_END = "# === end inbetween ===";

interface ClaudeJson {
  mcpServers?: Record<string, any>;
  [k: string]: any;
}

function readClaudeJson(path: string): ClaudeJson {
  if (!existsSync(path)) return {};
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    return {};
  }
}

/** Write Claude MCP entry. `local=true` writes <cwd>/.mcp.json (project-scoped). */
export function writeClaudeMcp(opts: {
  configFile: string; // absolute path to InBetween config.json
  local?: boolean;
  cwd?: string;
}): string {
  const cwd = opts.cwd || process.cwd();
  const path = opts.local ? claudeProjectMcpPath(cwd) : claudeUserConfigPath();
  const json = readClaudeJson(path);
  json.mcpServers = json.mcpServers || {};
  // Drop old agentgram entry if present (rebrand cleanup).
  if (json.mcpServers.agentgram) delete json.mcpServers.agentgram;
  json.mcpServers.inbetween = IS_WIN
    ? {
        command: "cmd",
        args: ["/c", "npx", "-y", MCP_PACKAGE],
        env: { INBETWEEN_CONFIG_PATH: opts.configFile },
      }
    : {
        command: "npx",
        args: ["-y", MCP_PACKAGE],
        env: { INBETWEEN_CONFIG_PATH: opts.configFile },
      };
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(json, null, 2) + "\n");
  return path;
}

export function removeClaudeMcp(opts: { local?: boolean; cwd?: string }): string | null {
  const cwd = opts.cwd || process.cwd();
  const path = opts.local ? claudeProjectMcpPath(cwd) : claudeUserConfigPath();
  if (!existsSync(path)) return null;
  const json = readClaudeJson(path);
  if (!json.mcpServers || !json.mcpServers.inbetween) return null;
  delete json.mcpServers.inbetween;
  writeFileSync(path, JSON.stringify(json, null, 2) + "\n");
  return path;
}

/** Write Codex MCP entry. `local=true` writes <cwd>/.inbetween/codex/config.toml (used with CODEX_HOME). */
export function writeCodexMcp(opts: {
  configFile: string; // absolute path to InBetween config.json
  local?: boolean;
  cwd?: string;
}): string {
  const cwd = opts.cwd || process.cwd();
  const path = opts.local ? codexLocalConfigPath(cwd) : codexHomeConfigPath();
  let existing = "";
  if (existsSync(path)) {
    try {
      existing = readFileSync(path, "utf-8");
    } catch {}
  }
  const escapedConfigFile = opts.configFile.replace(/\\/g, "\\\\");
  const command = IS_WIN ? "cmd" : "npx";
  const args = IS_WIN ? ["/c", "npx", "-y", MCP_PACKAGE] : ["-y", MCP_PACKAGE];
  const argsToml = JSON.stringify(args);
  const block = `${MCP_BLOCK_START}
[mcp_servers.inbetween]
command = "${command}"
args = ${argsToml}
env = { INBETWEEN_CONFIG_PATH = "${escapedConfigFile}", INBETWEEN_DISABLE_WS = "1" }
startup_timeout_sec = 30
${MCP_BLOCK_END}
`;
  let next: string;
  if (existing.includes(MCP_BLOCK_START) && existing.includes(MCP_BLOCK_END)) {
    const startIdx = existing.indexOf(MCP_BLOCK_START);
    const endIdx = existing.indexOf(MCP_BLOCK_END) + MCP_BLOCK_END.length;
    next = existing.slice(0, startIdx) + block.trim() + "\n" + existing.slice(endIdx + 1);
  } else {
    next = (existing.trim() + "\n\n" + block).trimStart();
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, next);
  return path;
}

export function removeCodexMcp(opts: { local?: boolean; cwd?: string }): string | null {
  const cwd = opts.cwd || process.cwd();
  const path = opts.local ? codexLocalConfigPath(cwd) : codexHomeConfigPath();
  if (!existsSync(path)) return null;
  const existing = readFileSync(path, "utf-8");
  if (!existing.includes(MCP_BLOCK_START) || !existing.includes(MCP_BLOCK_END)) {
    return null;
  }
  const startIdx = existing.indexOf(MCP_BLOCK_START);
  const endIdx = existing.indexOf(MCP_BLOCK_END) + MCP_BLOCK_END.length;
  const next = (existing.slice(0, startIdx) + existing.slice(endIdx)).replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
  writeFileSync(path, next);
  return path;
}

export { codexLocalHome };
